moving images/reformatting buttons/Adding missing CMYK images for grey icon
CodeNow/styleguide pull request #17
Opened 2017-04-27 19:48 UTC by rickiesherman

Wrapping up the content editing in styleguide. Thanks to Taylor and Tony for helping me :)

2017-04-29 01:02 UTC, runnabro commented on src/html/runnabear.html
> +      <a class="btn btn-xs white" href="images/bears/RGB/error-bear.png" Download PNG>Download PNG</a>
Shouldn't have PNG in the attribute

2017-05-02 00:54 UTC, taylordolan requested changes

2017-05-02 00:54 UTC, taylordolan commented on src/images/logo/gray-icon/CMYK/gray-icon.svg
> +<?xml version="1.0" encoding="utf-8"?>
This should be minified.

2017-05-02 00:54 UTC, taylordolan commented on src/html/runnabear.html
> +      <a class="btn btn-xs white" href="images/bears/RGB/basic-bear.png" Download>Download PNG</a>
Looks like this first figure is missing its closing tag:
![image](https://cloud.githubusercontent.com/assets/7440805/25600180/28ac81a0-2e97-11e7-90c6-6e23aab9c79f.png)

2017-05-02 23:47 UTC, rickiesherman commented on src/html/runnabear.html
> +      <a class="btn btn-xs white" href="images/bears/RGB/basic-bear.png" Download>Download PNG</a>
oop, got it

2017-05-02 23:47 UTC, rickiesherman commented on src/images/logo/gray-icon/CMYK/gray-icon.svg
> +<?xml version="1.0" encoding="utf-8"?>
👍

2017-05-03 00:21 UTC, taylordolan approved these changes

2017-05-03 00:28 UTC, taylordolan requested changes

2017-05-03 00:28 UTC, taylordolan commented on src/html/logo.html
> +      <img class="img" src="images/logo/pink-icon/RGB/runnable-icon-pink-rgb.svg" width="292" alt="Lockup Purple">
All images should have both `width` and `height` attributes. Let's go ahead and add any attributes that are missing to the logos/icons and bears.

2017-05-04 18:46 UTC, runnabro commented on src/html/logo.html
> +  <!-- section -->
Unnecessary indent?

2017-05-04 18:49 UTC, merged